// Organization Enums (avoid name clash with existing interfaces)

export enum DepartmentCode {
  MANAGEMENT = 'MANAGEMENT',
  SECURITY = 'SECURITY',
  MAINTENANCE = 'MAINTENANCE',
  CLEANING = 'CLEANING',
  LANDSCAPING = 'LANDSCAPING',
  ACCOUNTING = 'ACCOUNTING',
  FRONT_OFFICE = 'FRONT_OFFICE',
  RESIDENT_RELATIONS = 'RESIDENT_RELATIONS',
  LOGISTICS = 'LOGISTICS',
  IT = 'IT',
  HEALTH_SAFETY = 'HEALTH_SAFETY',
  SOCIAL_FACILITIES = 'SOCIAL_FACILITIES',
  WASTE_MANAGEMENT = 'WASTE_MANAGEMENT',
  PROCUREMENT = 'PROCUREMENT',
  PARKING = 'PARKING',
}

export enum PositionCode {
  SITE_MANAGER = 'SITE_MANAGER',
  ASSISTANT_SITE_MANAGER = 'ASSISTANT_SITE_MANAGER',
  SECURITY_SUPERVISOR = 'SECURITY_SUPERVISOR',
  SECURITY_OFFICER = 'SECURITY_OFFICER',
  MAINTENANCE_SUPERVISOR = 'MAINTENANCE_SUPERVISOR',
  TECHNICIAN_ELECTRICAL = 'TECHNICIAN_ELECTRICAL',
  TECHNICIAN_PLUMBING = 'TECHNICIAN_PLUMBING',
  TECHNICIAN_HVAC = 'TECHNICIAN_HVAC',
  CLEANING_SUPERVISOR = 'CLEANING_SUPERVISOR',
  CLEANER = 'CLEANER',
  GARDENER = 'GARDENER',
  LANDSCAPE_SUPERVISOR = 'LANDSCAPE_SUPERVISOR',
  ACCOUNTANT = 'ACCOUNTANT',
  CASHIER = 'CASHIER',
  FRONT_DESK_AGENT = 'FRONT_DESK_AGENT',
  RESIDENT_RELATIONS_SPECIALIST = 'RESIDENT_RELATIONS_SPECIALIST',
  LOGISTICS_COORDINATOR = 'LOGISTICS_COORDINATOR',
  IT_SUPPORT = 'IT_SUPPORT',
  HSE_OFFICER = 'HSE_OFFICER',
  FACILITY_SUPERVISOR = 'FACILITY_SUPERVISOR',
  POOL_ATTENDANT = 'POOL_ATTENDANT',
  FITNESS_TRAINER = 'FITNESS_TRAINER',
  WASTE_COLLECTION_STAFF = 'WASTE_COLLECTION_STAFF',
  PROCUREMENT_SPECIALIST = 'PROCUREMENT_SPECIALIST',
  PARKING_ATTENDANT = 'PARKING_ATTENDANT',
}


